### ISSUE TITLE
Move C# base classes to a nuget package

### ISSUE THREAD

**Issue by jenol** [agoda-com/graphql-codegen-csharp#34]
We should move the 

```Error.cs
IResultProcessor.cs
Location.cs
QueryBase.cs
QueryInvocationException.cs
Result.cs
DefaultResultProcessor.cs
```

classes to a nuget package ASAP

**Comment by dicko2** [comment]
Why?

**Comment by jenol** [comment]
these will not change often but generated regardless. The mobile team had add these to their project manually the same way they do the client. I want to tie these to the template version. I want to put the LINQ stuff into the nuget as well. 

I also want to have unit tests for these classes. If it is a C# project I can have a nunit test. Currently we have unit tests in homes which is not cool.

**Comment by jenol** [comment]
https://www.nuget.org/packages/Agoda.CodeGen.GraphQL/
